=== Momper14/DB2_Prak2/src/xml/ARTIKEL.dtd
<!ELEMENT artikellist (artikel*)>
<!ELEMENT artikel (artnr, artbez?, mge?, preis?, kuehl, edat?)>
<!ELEMENT artnr (#PCDATA)>
<!ATTLIST artnr DT CDATA #FIXED "number">
<!ELEMENT artbez (#PCDATA)>
<!ATTLIST artbez DT CDATA #FIXED "varchar2(30)">
<!ELEMENT mge (#PCDATA)>
<!ATTLIST mge DT CDATA #FIXED "varchar2(30)">
<!ELEMENT preis (#PCDATA)>
<!ATTLIST preis DT CDATA #FIXED "number(8,2)">
<!ELEMENT kuehl (#PCDATA)>
<!ATTLIST kuehl DT CDATA #FIXED "varchar2(2)">
<!ELEMENT edat (#PCDATA)>
<!ATTLIST edat DT CDATA #FIXED "date">

=== Momper14/DB2_Prak2/src/xml/ARTIKEL.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE artikellist SYSTEM "ARTIKEL.dtd">
<artikellist>
    <artikel>
        <artnr DT="number">1</artnr>
        <artbez DT="varchar2(30)">Milch</artbez>
        <mge DT="varchar2(30)">1 Liter</mge>
        <preis DT="number(8,2)">1.99</preis>
        <kuehl DT="varchar2(2)">KS</kuehl>
        <edat DT="date">2.2.2002</edat>
    </artikel>
    <artikel>
        <artnr DT="number">2</artnr>
        <artbez DT="varchar2(30)">Avocado</artbez>
        <mge DT="varchar2(30)">STK</mge>
        <preis DT="number(8,2)">4.99</preis>
        <kuehl DT="varchar2(2)">NK</kuehl>
        <edat DT="date">1.5.2005</edat>
    </artikel>
    <artikel>
        <artnr DT="number">3</artnr>
        <artbez DT="varchar2(30)">Spinat</artbez>
        <mge DT="varchar2(30)">250 gr</mge>
        <preis DT="number(8,2)">2.99</preis>
        <kuehl DT="varchar2(2)">TK</kuehl>
        <edat DT="date">12.12.2012</edat>
    </artikel>
    <artikel>
        <artnr DT="number">4</artnr>
        <artbez DT="varchar2(30)">Sojamilch</artbez>
        <mge DT="varchar2(30)">Liter</mge>
        <preis DT="number(8,2)">1.99</preis>
        <kuehl DT="varchar2(2)">NK</kuehl>
        <edat DT="date">13.1.2010</edat>
    </artikel>
    <artikel>
        <artnr DT="number">5</artnr>
        <artbez DT="varchar2(30)">Mais</artbez>
        <mge DT="varchar2(30)">100 gr</mge>
        <preis DT="number(8,2)">0.99</preis>
        <kuehl DT="varchar2(2)">NK</kuehl>
        <edat DT="date">7.3.1999</edat>
    </artikel>
</artikellist>
