=== Momper14/DB2_Prak2/src/xml/BESTELLAT.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:complexType name="besta">
    <xs:sequence>
      <xs:element name="artnr" type="xs:nonNegativeInteger" />
      <xs:element name="menge" type="xs:nonNegativeInteger" />
      <xs:element name="wert" type="xs:decimal" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="artlist">
    <xs:sequence>
      <xs:element name="besta" minOccurs="0" maxOccurs="unbounded" type="besta" />
    </xs:sequence>
  </xs:complexType>

  <xs:element name="bestellunglist">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="bestellung" minOccurs="1" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="bstnr" type="xs:nonNegativeInteger" />
              <xs:element name="knr" type="xs:nonNegativeInteger" />
              <xs:element name="status" type="xs:integer" />
              <xs:element name="rsum" type="xs:decimal" />
              <xs:element name="bestdat" type="xs:date" />
              <xs:element name="liefdat" type="xs:date" />
              <xs:element name="rechdat" type="xs:date" />
              <xs:element name="artlist" minOccurs="0" type="artlist" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Momper14/DB2_Prak2/src/xml/BESTELLAT.xml
<?xml version="1.0" encoding="UTF-8"?>
<bestellunglist xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="BESTELLAT.xsd">

    <bestellung>
        <bstnr>1</bstnr>
        <knr>1</knr>
        <status>1</status>
        <rsum>139.99</rsum>
        <bestdat>2003-12-15</bestdat>
        <liefdat>2003-12-20</liefdat>
        <rechdat>2003-12-27</rechdat>
        <artlist>
            <besta>
                <artnr>3</artnr>
                <menge>5</menge>
                <wert>20.0</wert>
            </besta>
            <besta>
                <artnr>4</artnr>
                <menge>2</menge>
                <wert>10.0</wert>
            </besta>
            <besta>
                <artnr>1</artnr>
                <menge>1</menge>
                <wert>19.99</wert>
            </besta>
        </artlist>
    </bestellung>

    <bestellung>
        <bstnr>2</bstnr>
        <knr>1</knr>
        <status>2</status>
        <rsum>109.99</rsum>
        <bestdat>2005-12-15</bestdat>
        <liefdat>2005-12-20</liefdat>
        <rechdat>2005-12-27</rechdat>
        <artlist>
            <besta>
                <artnr>3</artnr>
                <menge>5</menge>
                <wert>10.0</wert>
            </besta>
            <besta>
                <artnr>4</artnr>
                <menge>2</menge>
                <wert>20.0</wert>
            </besta>
            <besta>
                <artnr>1</artnr>
                <menge>1</menge>
                <wert>19.99</wert>
            </besta>
        </artlist>
    </bestellung>

</bestellunglist>
